apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.config.edge_video_analytics_microservice.name }}
  namespace: {{ $.Values.namespace }}
spec:
  type: NodePort
  ports:
    - name: "rest-api"
      port: {{ $.Values.config.edge_video_analytics_microservice.int.rest_api_port }}
      targetPort: {{ $.Values.config.edge_video_analytics_microservice.int.rest_api_port }}
      nodePort: {{ $.Values.config.edge_video_analytics_microservice.ext.rest_api_port }}
    - name: "rtsp-output-streaming"
      port: {{ $.Values.config.edge_video_analytics_microservice.int.rtsp_output_port }}
      targetPort: {{ $.Values.config.edge_video_analytics_microservice.int.rtsp_output_port }}
      nodePort: {{ $.Values.config.edge_video_analytics_microservice.ext.rtsp_output_port }}
  selector:
    app: edge-video-analytics-microservice
