name: 'Setup Tools'
description: 'Sets up Python, Poetry, Trivy, and other required tools'

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Poetry
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Install Trivy
      shell: bash
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
    
    - name: Install Python Dependencies
      shell: bash
      run: |
        pip install pytest pytest-cov

    - name: Setup Node.js with NVM
      shell: bash
      run: |
        # Download and install nvm
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash
        
        # In lieu of restarting the shell
        . "$HOME/.nvm/nvm.sh"
        
        # Download and install Node.js
        nvm install 22
        
        # Verify the Node.js version
        node -v
        nvm current
        
        # Verify npm version
        npm -v
        
        # Install vitest
        npm install -D vitest@2.1.9
