---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Folder-Specific CI for PRs

on:
  push:
    branches:
      - ga-new-actions  
    paths:
      - 'sample-applications/chat-question-and-answer-core/**'
      - 'sample-applications/chat-question-and-answer/**'
  
  pull_request:
    branches:
      - ga-new-actions
    paths:
      - 'sample-applications/chat-question-and-answer-core/**'
      - 'sample-applications/chat-question-and-answer/**'    

jobs:
  detect-changes:
    runs-on: ubuntu-24.04-16core-64GB
    outputs:
      core_changed: ${{ steps.filter.outputs.core_changed }}
      qa_changed: ${{ steps.filter.outputs.qa_changed }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Filter Changes
        id: filter
        run: |
          # Determine the comparison based on event type
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "Event: Pull Request"
            # For pull requests, compare against the PR base
            git fetch origin ${{ github.event.pull_request.base.sha }} --depth=1
            BASE_SHA=${{ github.event.pull_request.base.sha }}
            HEAD_SHA=${{ github.event.pull_request.head.sha }}
          else
            echo "Event: Push"
            # For pushes, compare against the previous commit
            git fetch origin ${{ github.event.before }} --depth=1
            BASE_SHA=${{ github.event.before }}
            HEAD_SHA=${{ github.sha }}
          fi
          
          echo "Comparing $BASE_SHA...$HEAD_SHA"
          
          # Check if core folder has changes
          if git diff --name-only $BASE_SHA $HEAD_SHA | grep -q "^sample-applications/chat-question-and-answer-core/"; then
            echo "Core folder has changes"
            echo "core_changed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes in core folder"
            echo "core_changed=false" >> $GITHUB_OUTPUT
          fi
          
          # Check if Q&A folder has changes
          if git diff --name-only $BASE_SHA $HEAD_SHA | grep -q "^sample-applications/chat-question-and-answer/"; then
            echo "Q&A folder has changes"
            echo "qa_changed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes in Q&A folder"
            echo "qa_changed=false" >> $GITHUB_OUTPUT
          fi

  core-job:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.core_changed == 'true' }}
    runs-on: ubuntu-24.04-16core-64GB
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Run Commands for Core
        run: |
          cd sample-applications/chat-question-and-answer-core
          # Add your commands here
          echo "Running commands for chat-question-and-answer-core"

  qa-job:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.qa_changed == 'true' }}
    runs-on: ubuntu-24.04-16core-64GB
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Run Commands for Q&A
        run: |
          cd sample-applications/chat-question-and-answer
          # Add your commands here
          echo "Running commands for chat-question-and-answer"
