---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Folder-Specific CI for PRs

on:
  push:
    branches:
      - ga-new-actions  
    paths:
      - 'sample-applications/chat-question-and-answer-core/**'
      - 'sample-applications/chat-question-and-answer/**'

jobs:
  detect-changes:
    runs-on: ubuntu-24.04-16core-64GB
    outputs:
      core_changed: ${{ steps.filter.outputs.core_changed }}
      qa_changed: ${{ steps.filter.outputs.qa_changed }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Filter Changes
        id: filter
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          
          # Check if core folder has changes
          if git diff --name-only origin/${{ github.base_ref }} HEAD | grep -q "^sample-applications/chat-question-and-answer-core/"; then
            echo "core_changed=true" >> $GITHUB_OUTPUT
          else
            echo "core_changed=false" >> $GITHUB_OUTPUT
          fi
          
          # Check if Q&A folder has changes
          if git diff --name-only origin/${{ github.base_ref }} HEAD | grep -q "^sample-applications/chat-question-and-answer/"; then
            echo "qa_changed=true" >> $GITHUB_OUTPUT
          else
            echo "qa_changed=false" >> $GITHUB_OUTPUT
          fi

  core-job:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.core_changed == 'true' }}
    runs-on: ubuntu-24.04-16core-64GB
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Run Commands for Core
        run: |
          cd sample-applications/chat-question-and-answer-core
          # Add your commands here
          echo "Running commands for chat-question-and-answer-core"

  qa-job:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.qa_changed == 'true' }}
    runs-on: ubuntu-24.04-16core-64GB
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Run Commands for Q&A
        run: |
          cd sample-applications/chat-question-and-answer
          # Add your commands here
          echo "Running commands for chat-question-and-answer"
          PUBLISH=$(echo "$PR_DESCRIPTION" | grep -q '/publish🚢' && echo true || echo false)
          echo $PUBLISH
          echo "PUBLISH=$PUBLISH" >> $GITHUB_ENV
