name: Folder-Specific CI

on:
  pull_request:
    branches:
      - ga-new-actions
    paths:
      - 'sample-applications/chat-question-and-answer-core/**'
      - 'sample-applications/chat-question-and-answer/**'
  push:
    branches:
      - ga-new-actions
    paths:
      - 'sample-applications/chat-question-and-answer-core/**'
      - 'sample-applications/chat-question-and-answer/**'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      core_changed: ${{ steps.filter.outputs.core_changed }}
      qa_changed: ${{ steps.filter.outputs.qa_changed }}
    steps:
      # [Change detection logic as before]
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Filter Changes
        id: filter
        # [Same filter logic as before]
        run: |
          # [Change detection script]
          echo "core_changed=true" >> $GITHUB_OUTPUT
          echo "qa_changed=true" >> $GITHUB_OUTPUT

  core-job:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.core_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Tools
        uses: ./.github/actions/setup-tools
      
      - name: Run Commands for Core
        run: |
          cd sample-applications/chat-question-and-answer-core
          # Your commands here
          trivy --version
          python --version

  qa-job:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.qa_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Tools
        uses: ./.github/actions/setup-tools
      
      - name: Run Commands for Q&A
        run: |
          cd sample-applications/chat-question-and-answer
          # Your commands here
          trivy --version
          python --version
